### ISSUE TITLE
Distribute wheel files

### ISSUE THREAD

**Issue by jaap3** [wagtail/telepath#6]
Currently there's only a `.tar.gz` `sdist` on PyPI. This causes `pip` to build a wheel each time `telepath` is installed. It should be possible to create a wheel when releasing telepath to PyPI, making installs of `telepath` faster.

I think adding a `setup.cfg` with the following content should do the trick?

```
[bdist_wheel]
python-tag = py35
```

**Comment by dchimeno** [comment]
just came across this https://github.com/pypa/cibuildwheel today in case it's useful (which it seems)

**Comment by gasman** [comment]
Thanks for reporting! 0.2 now released, including a wheel package.
